export const PRODUCTS = [
  {
    id: "tender-coconut",
    name: "Tender Coconut",
    accent: "#7FA33A",
    image: "/products/tender-coconut1.png",
    fruit: "/fruits/coconut.png",
    short: "Fresh & Hydrating.",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    accent: "#D4114A",
    image: "/products/strawberry2.png",
    fruit: "/fruits/strawberry.png",
    short: "Sweet. Vibrant. Premium.",
  },
  {
    id: "chikku",
    name: "Chikku",
    accent: "#A8752F",
    image: "/products/chikku1.png",
    fruit: "/fruits/chikku.png",
    short: "Creamy Tropical Delight.",
  },
  {
    id: "mango",
    name: "Mango",
    accent: "#FF9A19",
    image: "/products/mango2.png",
    fruit: "/fruits/mango.png",
    short: "Rich Golden Pulp.",
  },
  {
    id: "avocado",
    name: "Avocado",
    accent: "#6A8E3D",
    image: "/products/avocado1.png",
    fruit: "/fruits/avocado.png",
    short: "Smooth & Nourishing.",
  },
  {
    id: "custard-apple",
    name: "Custard Apple",
    accent: "#3D7A2B",
    image: "/products/custard-apple1.png",
    fruit: "/fruits/custard-apple.png",
    short: "Soft. Sweet. Fragrant.",
  },
];
